<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Admin-Pc" name="runner.RunTest" tests="4" failures="0" timestamp="2019-11-06T13:28:11 IST" time="25.646" errors="4">
  <testcase name="runScenario" time="6.088" classname="runner.RunTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at steps.Login.enter_Username_as_DemoSalesmanager(Login.java:24)
at ✽.Enter Username as DemoCSR(file:src/test/java/features/Login.feature:5)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="5.958" classname="runner.RunTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at steps.Login.enter_Username_as_DemoSalesmanager(Login.java:24)
at ✽.Enter Username as Demosalesmanager(file:src/test/java/features/Login.feature:5)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="7.021" classname="runner.RunTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at steps.Login.enter_Username_as_DemoSalesmanager(Login.java:24)
at ✽.Enter Username as DemoSalesmanager(file:src/test/java/features/invalidLogin.feature:4)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="6.579" classname="runner.RunTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at steps.Login.enter_Username_as_DemoSalesmanager(Login.java:24)
at ✽.Enter Username as DemoSalesmanager(file:src/test/java/features/Login.feature:15)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.RunTest -->
